
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/llvm-mingw-20240619-msvcrt-x86_64/bin/cc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdC/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:17 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva"
      binary: "C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2024.1.4/bin/ninja/win/x64/ninja.exe" -v cmTC_07ad5
        [1/2] C:\\llvm-mingw-20240619-msvcrt-x86_64\\bin\\cc.exe   -fansi-escape-codes -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_07ad5.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -c "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeCCompilerABI.c"
        clang version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)
        Target: x86_64-w64-windows-gnu
        Thread model: posix
        InstalledDir: C:/llvm-mingw-20240619-msvcrt-x86_64/bin
         (in-process)
         "C:/llvm-mingw-20240619-msvcrt-x86_64/bin/clang-18.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva -v -fcoverage-compilation-dir=C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva -resource-dir C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18 -dependency-file "CMakeFiles\\\\cmTC_07ad5.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -sys-header-deps -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/include -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/usr/include -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/include -ferror-limit 19 -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -exception-model=seh -fcolor-diagnostics -fansi-escape-codes -faddrsig -o CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -x c "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeCCompilerABI.c"
        clang -cc1 version 18.1.8 based upon LLVM 18.1.8 default target x86_64-w64-mingw32
        ignoring nonexistent directory "C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/include"
        ignoring nonexistent directory "C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/usr/include"\x0d
        #include "..." search starts here:\x0d
        #include <...> search starts here:\x0d
         C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include\x0d
         C:/llvm-mingw-20240619-msvcrt-x86_64/include\x0d
        End of search list.\x0d
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\llvm-mingw-20240619-msvcrt-x86_64\\bin\\cc.exe  -v CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -o cmTC_07ad5.exe -Wl,--out-implib,libcmTC_07ad5.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        clang version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)
        Target: x86_64-w64-windows-gnu
        Thread model: posix
        InstalledDir: C:/llvm-mingw-20240619-msvcrt-x86_64/bin
         "C:/llvm-mingw-20240619-msvcrt-x86_64/bin/ld.lld" -m i386pep -Bdynamic -o cmTC_07ad5.exe C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crt2.o C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtbegin.o -LC:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib -LC:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib -LC:/llvm-mingw-20240619-msvcrt-x86_64/lib -LC:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_07ad5.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a -lunwind -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a -lunwind -lmoldname -lmingwex -lmsvcrt -lkernel32 C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtend.o\x0d
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include]
          add: [C:/llvm-mingw-20240619-msvcrt-x86_64/include]
        end of search list found
        collapse include dir [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include] ==> [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include]
        collapse include dir [C:/llvm-mingw-20240619-msvcrt-x86_64/include] ==> [C:/llvm-mingw-20240619-msvcrt-x86_64/include]
        implicit include dirs: [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include;C:/llvm-mingw-20240619-msvcrt-x86_64/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld\\.lld\\.exe|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: 'C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva']
        ignore line: []
        ignore line: [Run Build Command(s): "C:/Program Files/JetBrains/CLion 2024.1.4/bin/ninja/win/x64/ninja.exe" -v cmTC_07ad5]
        ignore line: [[1/2] C:\\llvm-mingw-20240619-msvcrt-x86_64\\bin\\cc.exe   -fansi-escape-codes -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_07ad5.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -c "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeCCompilerABI.c"]
        ignore line: [clang version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)]
        ignore line: [Target: x86_64-w64-windows-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: C:/llvm-mingw-20240619-msvcrt-x86_64/bin]
        ignore line: [ (in-process)]
        ignore line: [ "C:/llvm-mingw-20240619-msvcrt-x86_64/bin/clang-18.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva -v -fcoverage-compilation-dir=C:/Users/User/CLionProjects/Tex_poker/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-um7dva -resource-dir C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18 -dependency-file "CMakeFiles\\\\cmTC_07ad5.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -sys-header-deps -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/include -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/usr/include -internal-isystem C:/llvm-mingw-20240619-msvcrt-x86_64/include -ferror-limit 19 -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -exception-model=seh -fcolor-diagnostics -fansi-escape-codes -faddrsig -o CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -x c "C:/Program Files/JetBrains/CLion 2024.1.4/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeCCompilerABI.c"]
        ignore line: [clang -cc1 version 18.1.8 based upon LLVM 18.1.8 default target x86_64-w64-mingw32]
        ignore line: [ignoring nonexistent directory "C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/include"]
        ignore line: [ignoring nonexistent directory "C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/usr/include"\x0d]
        ignore line: [#include "..." search starts here:\x0d]
        ignore line: [#include <...> search starts here:\x0d]
        ignore line: [ C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/include\x0d]
        ignore line: [ C:/llvm-mingw-20240619-msvcrt-x86_64/include\x0d]
        ignore line: [End of search list.\x0d]
        ignore line: [[2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\llvm-mingw-20240619-msvcrt-x86_64\\bin\\cc.exe  -v CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj -o cmTC_07ad5.exe -Wl --out-implib libcmTC_07ad5.dll.a -Wl --major-image-version 0 --minor-image-version 0   && cd ."]
        ignore line: [clang version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)]
        ignore line: [Target: x86_64-w64-windows-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: C:/llvm-mingw-20240619-msvcrt-x86_64/bin]
        link line: [ "C:/llvm-mingw-20240619-msvcrt-x86_64/bin/ld.lld" -m i386pep -Bdynamic -o cmTC_07ad5.exe C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crt2.o C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtbegin.o -LC:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib -LC:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib -LC:/llvm-mingw-20240619-msvcrt-x86_64/lib -LC:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_07ad5.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a -lunwind -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a -lunwind -lmoldname -lmingwex -lmsvcrt -lkernel32 C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtend.o\x0d]
          arg [C:/llvm-mingw-20240619-msvcrt-x86_64/bin/ld.lld] ==> ignore
          arg [-m] ==> ignore
          arg [i386pep] ==> ignore
          arg [-Bdynamic] ==> search dynamic
          arg [-o] ==> ignore
          arg [cmTC_07ad5.exe] ==> ignore
          arg [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crt2.o] ==> obj [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crt2.o]
          arg [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtbegin.o] ==> obj [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtbegin.o]
          arg [-LC:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib] ==> dir [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib]
          arg [-LC:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib] ==> dir [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib]
          arg [-LC:/llvm-mingw-20240619-msvcrt-x86_64/lib] ==> dir [C:/llvm-mingw-20240619-msvcrt-x86_64/lib]
          arg [-LC:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows] ==> dir [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows]
          arg [CMakeFiles/cmTC_07ad5.dir/CMakeCCompilerABI.c.obj] ==> ignore
          arg [--out-implib] ==> ignore
          arg [libcmTC_07ad5.dll.a] ==> ignore
          arg [--major-image-version] ==> ignore
          arg [0] ==> ignore
          arg [--minor-image-version] ==> ignore
          arg [0] ==> ignore
          arg [-lmingw32] ==> lib [mingw32]
          arg [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a] ==> lib [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a]
          arg [-lunwind] ==> lib [unwind]
          arg [-lmoldname] ==> lib [moldname]
          arg [-lmingwex] ==> lib [mingwex]
          arg [-lmsvcrt] ==> lib [msvcrt]
          arg [-ladvapi32] ==> lib [advapi32]
          arg [-lshell32] ==> lib [shell32]
          arg [-luser32] ==> lib [user32]
          arg [-lkernel32] ==> lib [kernel32]
          arg [-lmingw32] ==> lib [mingw32]
          arg [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a] ==> lib [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a]
          arg [-lunwind] ==> lib [unwind]
          arg [-lmoldname] ==> lib [moldname]
          arg [-lmingwex] ==> lib [mingwex]
          arg [-lmsvcrt] ==> lib [msvcrt]
          arg [-lkernel32] ==> lib [kernel32]
          arg [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtend.o] ==> obj [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtend.o]
        remove lib [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a]
        remove lib [msvcrt]
        remove lib [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows/libclang_rt.builtins-x86_64.a]
        remove lib [msvcrt]
        collapse library dir [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib] ==> [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib]
        collapse library dir [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib] ==> [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib]
        collapse library dir [C:/llvm-mingw-20240619-msvcrt-x86_64/lib] ==> [C:/llvm-mingw-20240619-msvcrt-x86_64/lib]
        collapse library dir [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows] ==> [C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows]
        implicit libs: [mingw32;unwind;moldname;mingwex;advapi32;shell32;user32;kernel32;mingw32;unwind;moldname;mingwex;kernel32]
        implicit objs: [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crt2.o;C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtbegin.o;C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib/crtend.o]
        implicit dirs: [C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/lib;C:/llvm-mingw-20240619-msvcrt-x86_64/x86_64-w64-mingw32/mingw/lib;C:/llvm-mingw-20240619-msvcrt-x86_64/lib;C:/llvm-mingw-20240619-msvcrt-x86_64/lib/clang/18/lib/windows]
        implicit fwks: []
      
      
...
